.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "SOLARPOWERLOG" "1" "June 16, 2009" "" ""
.SH "NAME"
solarpowerlog \- queries data from a photovoltaic inverter
.SH "SYNOPSIS"
.B solarpowerlog
.RI [ options ] 
.br 
.SH "DESCRIPTION"
The program's purpose is to track and log data from photo\-voltaic inverters, collect power data and store them. Also a purpose is to provide an interface to extract these data, allowing applications like website statistics of the system.



.SH "OPTIONS"
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`\-').
A summary of options is included below.

.TP 
.B \-h, \-\-help
Show summary of options.
.TP 
.B \-v, \-\-version
Show version of program.
.TP 
.B \-b, \-\-background
Runs the program in the background, detaching it from the console.
.TP 
.B \-c, \-\-conf filename
The configuration to be used. Default is solarpowerlog.conf, looked for in the current directory. 
.TP 

.SH "SEE ALSO"
.SH "AUTHOR"
solarpowerlog was written by Tobias Frost
