Document: solarpowerlog
Title: Debian solarpowerlog Manual
Author: <insert document author here>
Abstract: This manual describes what solarpowerlog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/solarpowerlog/solarpowerlog.sgml.gz

Format: postscript
Files: /usr/share/doc/solarpowerlog/solarpowerlog.ps.gz

Format: text
Files: /usr/share/doc/solarpowerlog/solarpowerlog.text.gz

Format: HTML
Index: /usr/share/doc/solarpowerlog/html/index.html
Files: /usr/share/doc/solarpowerlog/html/*.html
