#!/bin/bash

# dpkg-buildpackage the debian package

# Prerequesite:
# builbot_make_orig_source run 

# Result:
# hopfully a debian package...

set -e

VERSION=$(grep "PACKAGE_VERSION=" configure | cut -d"=" -f 2- | tr --delete "\'")

( cd stagedir_debbuild/solarpowerlog-$VERSION && dpkg-buildpackage -uc -us )


