#!/bin/bash

# Prepare the build-dir for the debian package

# Prerequesite:
# make dist done by buildbot
# make dist will place a cp solarpowerlog-$VERSION.tar.gz in the builddir.

# Result:
# stagedir_debbuild contains untarred source and orig.tar.gz, debian dir integrated
# debian changelog contains buildbot information.

set -e


VERSION=$(grep "PACKAGE_VERSION=" configure | cut -d"=" -f 2- | tr --delete "\'")

# copy orig.tar.gz into position
rm -rf   stagedir_debbuild
mkdir -p stagedir_debbuild
mv solarpowerlog-$VERSION.tar.gz stagedir_debbuild/solarpowerlog_$VERSION.orig.tar.gz

# extract it
( cd stagedir_debbuild && tar xzf solarpowerlog_$VERSION.orig.tar.gz)

# copy debian dir 
cp -r debian stagedir_debbuild/solarpowerlog-$VERSION 

# record that we are autobuilding.
GIT_DESCRIBE=$(git describe)
( cd stagedir_debbuild/solarpowerlog-$VERSION && dch -a "buildbot built. git-describe: $GIT_DESCRIBE" )


